pipeline:
  name: python-helloWorld
  identifier: pythonhelloWorld
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1702454246010
        repoName: NavjitK/python2
        build: <+input>
  stages:
    - stage:
        name: Docker_Build
        identifier: Docker_Build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Windows
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: docker build -t python-hello-world .
